[package]
name = "ntpuvpn-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
net-route = "0.4.6"
pnet = "0.35.0"
rpassword = "7.4.0"
serde = { version = "1.0.225", features = ["derive"] }
tempfile = "3.22.0"
tun-rs = "2.7.3"

